---
# https://taskfile.dev
version: '3'
tasks:
  install:
    desc: ðŸ› ï¸ [agent_llamaindex] Update local dependencies
    cmds:
      - echo "Updating local dependencies"
      - uv sync --all-extras
      - cd custom_model && uv pip install -r requirements.txt
    silent: true
    aliases:
      - req
  update:
    desc: ðŸ› ï¸ [agent_llamaindex] Update local dependencies (refresh uv locks)
    cmds:
      - echo "Updating local dependencies"
      - uv sync --all-extras -U
      - cd custom_model && uv pip install -r requirements.txt
    silent: true
  lint:
    desc: ðŸ§¹ [agent_llamaindex] Lint the codebase
    cmds:
      - task: req
      - echo "Linting the codebase"
      - uv run ruff check . --fix
      - uv run ruff format .
      - uv run mypy --pretty .
      - uv run yamlfix custom_model
    silent: true
  lint-check:
    desc: ðŸ§¹ [agent_llamaindex] Check whether the codebase is linted
    cmds:
      - task: req
      - echo "Checking linting"
      - uv run ruff format --check --diff .
      - uv run ruff check --diff .
      - uv run mypy --pretty .
    silent: true
  test:
    desc: ðŸ§ª [agent_llamaindex] Run tests
    cmds:
      - echo "Running pytest on tests"
      - uv run pytest -vv ./tests/
    silent: true
  test-coverage:
    desc: ðŸ§ª [agent_llamaindex] Run tests with coverage
    cmds:
      - echo "Running pytest on tests"
      - uv run pytest -vv --cov --cov-report=html --cov-report=term --cov-report xml:.coverage.xml ./tests/
    silent: true
  cli:
    desc: ðŸ–¥ï¸ [agent_llamaindex] Run the CLI with provided arguments
    cmds:
      - echo "Running CLI {{.CLI_ARGS}}"
      - uv run cli.py {{.CLI_ARGS}}
    silent: true
  dev:
    desc: ðŸ”¨[agent_llamaindex] Run the development server
    env:
      TARGET_NAME: response
      FLASK_DEBUG: 1
    cmds:
      - echo "Running development server on http://localhost:8842"
      - uv run drum server -cd custom_model --address localhost:8842 --target-type agenticworkflow
      - wait
  build-docker:
    desc: ðŸ³ [agent_llamaindex] Build the Docker image
    cmds:
      - echo "Compiling requirements for Docker"
      - cd docker_context && uv pip compile --python-version 3.11 --universal --no-annotate --no-emit-index-url --output-file=requirements.txt
        requirements.in
      - echo "Building Docker image"
      - cd docker_context && docker build --platform linux/amd64 -f Dockerfile -t agent_llamaindex:latest .
      - echo "Saving Docker image"
      - docker save agent_llamaindex:latest | gzip > docker_context.tar.gz
    silent: true
