---
# https://taskfile.dev
version: '3'
env:
  ENV: testing
dotenv: ['.env', '.env.{{.ENV}}']
includes:
  agent:
    taskfile: ./agent_langgraph/Taskfile.yml
    dir: ./agent_langgraph
  web:
    taskfile: ./web/Taskfile.yaml
    dir: ./web
  frontend:
    taskfile: ./frontend_web/Taskfile.yaml
    dir: ./frontend_web
tasks:
  default:
    desc: "🗒️ Show all available tasks"
    cmds:
      - task --list
    silent: true
  install:
    desc: "🏗️ [agent_langgraph] Install and setup the agent and infra environments"
    cmds:
      - echo "Updating agent environment"
      - task: agent:req
      - task: web:install
      - task: frontend:install
      - echo "Updating infra environment"
      - cd ./infra && uv sync --all-extras
    silent: true
    aliases:
      - setup
      - req
  build:
    desc: "🔵 [agent_langgraph] Run Pulumi up in [BUILD] mode"
    env:
      AGENT_DEPLOY: 0
    cmds:
      - echo "Running pulumi up with [BUILD] mode"
      - "cd ./infra && {{.CLEAN_PYTHON_ENV}} uv run pulumi up {{.CLI_ARGS}}"
    silent: true
  deploy:
    desc: "🟢 [agent_langgraph] Run Pulumi up in [DEPLOY] mode"
    env:
      AGENT_DEPLOY: 1
    cmds:
      - echo "Running pulumi up with [DEPLOY] mode"
      - "cd ./infra && {{.CLEAN_PYTHON_ENV}} uv run pulumi up {{.CLI_ARGS}}"
    silent: true
  refresh:
    desc: "⚪️ [agent_langgraph] Run Pulumi refresh"
    cmds:
      - echo "Running pulumi refresh"
      - "cd ./infra && {{.CLEAN_PYTHON_ENV}} uv run pulumi refresh {{.CLI_ARGS}}"
    silent: true
  destroy:
    desc: "🔴 [agent_langgraph] Run Pulumi destroy"
    cmds:
      - echo "Running pulumi destroy"
      - "cd ./infra && {{.CLEAN_PYTHON_ENV}} uv run pulumi destroy {{.CLI_ARGS}}"
    silent: true
  lint:
    silent: true
    desc: "Run all linters."
    cmds:
      - task: agent:lint
      - task: web:lint
      - task: frontend:lint
  lint-check:
    silent: true
    desc: "Run all checks."
    cmds:
      - task: agent:lint-check
      - task: web:lint-check
      - task: frontend:lint-check
  dev:
    desc: "🔨Run the fastapi development server"
    cmds:
      - |
          task web:dev-agent &
          sleep 5
          task agent:dev &
          sleep 3
          task frontend:dev &
          sleep 8
          echo "✅ All servers started!"
          echo "🔗 Backend: http://localhost:8080"
          echo "🔗 Frontend: http://localhost:5173"
          echo "🔗 Agent: http://localhost:8842"
          wait
    silent: true