---
name: Test agent_generic_base
on:
  push:
    branches: ["main"]
    paths:
      - 'agent_generic_base/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'agent_generic_base/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    working-directory: agent_generic_base
jobs:
  drum-cli-tests-prompt:
    name: "DRUM: agent cli ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: "actions/checkout@v4"
      # Ref: https://docs.astral.sh/uv/guides/integration/github/#installation
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          uv sync --all-extras
          uv pip install git+https://github.com/datarobot-forks/litellm@mattn/add-datarobot-support-to-litellm
      - name: Run cli test
        run: |
          uv run cli.py execute --user_prompt '{"topic": "Artificial Intelligence"}'
          if uv run cli.py execute --user_prompt '{"topic": "Artificial Intelligence"}' | grep -q '"content": "success"'; then
            echo "Test passed: cli.py returned success"
          else
            echo "Test failed: cli.py did not return success"
            exit 1
          fi
  drum-cli-tests-json:
    name: "DRUM: agent cli ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: "actions/checkout@v4"
      # Ref: https://docs.astral.sh/uv/guides/integration/github/#installation
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          uv sync --all-extras
          uv pip install git+https://github.com/datarobot-forks/litellm@mattn/add-datarobot-support-to-litellm
      - name: Run cli test
        run: |
          uv run cli.py execute --completion_json "example-completion.json"
          if uv run cli.py execute --completion_json "example-completion.json" | grep -q '"content": "success"'; then
            echo "Test passed: cli.py returned success"
          else
            echo "Test failed: cli.py did not return success"
            exit 1
          fi
  docker-build-test:
    name: "Agent: agent_generic_base Docker build and test"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Build Docker Image
        run: |
          cd docker_context
          tar -czh . | docker build - -t agent_generic_base
  tests:
    name: "Agent: agent_generic_base ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: "actions/checkout@v4"
      # Ref: https://docs.astral.sh/uv/guides/integration/github/#installation
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          uv sync --all-extras --dev
          uv pip install -r ./custom_model/requirements.txt
      - name: Run Static Checks
        run: |
          uv run ruff format --check .
          uv run ruff check .
          uv run mypy --pretty .
      - name: Test
        run: uv run pytest --cov --cov-report=html --cov-report=term --cov-report xml:.coverage.xml
      - name: Get Cover
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: agent_generic_base/.coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
