---
name: Python Infra Checks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  python-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Ref: https://docs.astral.sh/uv/guides/integration/github/#installation
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: infra
          python-version: ${{ matrix.python-version }}

      - name: Install Taskfile
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        working-directory: infra
        run: task install

      - name: Run Static Checks
        working-directory: infra
        run: task lint-check
