---
name: License Header Check

on: push

jobs:
  license-header-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: License Header Check
        uses: apache/skywalking-eyes/header@main
        with:
          config: .github/.licenserc.yaml
