---
name: Shellcheck

on:
  push:
    paths:
      - '**.sh'
    branches:
      - main
      - 'release/*'
  pull_request:
    paths:
      - '**.sh'
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          wget -qO- https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz | tar -xJv
          sudo install -o root -g root -m 0755 shellcheck-stable/shellcheck /usr/local/bin
          shellcheck --version
      - name: Run shellcheck
        run: |
          find . -type f -name "*.sh" -exec shellcheck {} +
